/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CLientGUI;

import Client.GameThread;
import CLientGUI.QuestionGUI.AnswerInformer;
import Common.Question;
import com.alee.laf.WebLookAndFeel;
import java.awt.Graphics;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;
import java.util.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class QuestionGUI extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form Challenge
     */
    int time;
    Question q;
    TimerUpdate timer;
    boolean answer = false;
    AnswerInformer ansInfo;
    int n_question;
    public QuestionGUI() {
        //try {
            initComponents();
            
            //byte[] finalarr = Files.readAllBytes(Paths.get("Challenges\\imagens\\000003.jpg"));
            //this.imageContainer.add(new PaintImage(finalarr),"image");
            //timer = new TimerUpdate();
            
            //time = 60;
            //timer_lb.setText("1:00");
            //byte[] music = Files.readAllBytes(Paths.get("Challenges\\musica\\000003.mp3"));
            //init(music);
            
            //((CardLayout)jPanel1.getLayout()).show(jPanel1, "image");
        //} catch (IOException ex) {
          //  Logger.getLogger(QuestionGUI.class.getName()).log(Level.SEVERE, null, ex);
        //}
        
    }
    final void init(byte[][] music){
      
        try {
            timer.addObserver(this);
            QuestionRunner runner = new QuestionRunner(music,timer);
            
            //ao fechar enviar pedido de quit
            WindowListener exitListener = new WindowAdapterImpl(this.ansInfo, this,runner);
            this.addWindowListener(exitListener);
            
            runner.start();
        } catch (IOException ex) {
            Logger.getLogger(QuestionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public QuestionGUI(Question question,GameThread gt,int qt) {
        this.q = question;
        this.ansInfo = new AnswerInformer();
        ansInfo.addObserver(gt);
        initComponents();
        this.imageContainer.add(new PaintImage(q.getImage()),"image");
        this.answer1_lb.setText(q.getAnswer1());
        this.answer2_lb.setText(q.getAnswer2());
        this.answer3_lb.setText(q.getAnswer3());
        this.question.setText(q.getQuestion());
        timer = new TimerUpdate(); 
        time = 60;
        timer_lb.setText("1:00");
        //
        init(q.getMusic());
        //
        n_question  =qt;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        answer1 = new javax.swing.JButton();
        answer2 = new javax.swing.JButton();
        answer3 = new javax.swing.JButton();
        imageContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        timer_lb = new javax.swing.JLabel();
        answer1_lb = new javax.swing.JLabel();
        answer2_lb = new javax.swing.JLabel();
        answer3_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        answer1.setText("A");
        answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1ActionPerformed(evt);
            }
        });

        answer2.setText("B");
        answer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2ActionPerformed(evt);
            }
        });

        answer3.setText("C");
        answer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3ActionPerformed(evt);
            }
        });

        imageContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagem"));
        imageContainer.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/FAQ-icon.png"))); // NOI18N

        question.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        question.setText("exemplo de pergunta ? ");

        timer_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timer_lb.setText("0:59");

        answer1_lb.setText("resposta 1");

        answer2_lb.setText("resposta 2");

        answer3_lb.setText("resposta 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(question))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(imageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(answer1_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(answer2_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(answer3_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(timer_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(answer1_lb)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(answer2_lb)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(answer3_lb)))
                        .addGap(38, 38, 38)
                        .addComponent(timer_lb)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1ActionPerformed
        // TODO add your handling code here:
        this.ansInfo.answer(this.n_question, 1, this.time);
        this.answer = true;
    }//GEN-LAST:event_answer1ActionPerformed

    private void answer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2ActionPerformed
        this.ansInfo.answer(this.n_question, 2, this.time);
        this.answer = true;
    }//GEN-LAST:event_answer2ActionPerformed

    private void answer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3ActionPerformed
       this.ansInfo.answer(this.n_question, 3, this.time);
        this.answer = true;
    }//GEN-LAST:event_answer3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                boolean install = WebLookAndFeel.install(); 
                new QuestionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answer1;
    private javax.swing.JLabel answer1_lb;
    private javax.swing.JButton answer2;
    private javax.swing.JLabel answer2_lb;
    private javax.swing.JButton answer3;
    private javax.swing.JLabel answer3_lb;
    private javax.swing.JPanel imageContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel question;
    private javax.swing.JLabel timer_lb;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(java.util.Observable o, Object arg) {
        
            time = (int)arg;
            if(time>=60)
                this.timer_lb.setText("1:00");
            else
                if(time>=10)
                    this.timer_lb.setText("00:" + time);
                else
                    this.timer_lb.setText("00:0" + time);
        
        if(time==0)
        {
            this.ansInfo.answer(n_question, -1, time);
            this.dispose();
           
        }
    }

    public static class PaintImage extends JPanel 
    { 
       public BufferedImage image; 

      public PaintImage (byte[][] image) 
      { 
        super(); 
        try 
        {                
           //byte[] finalarr = Files.readAllBytes(Paths.get("Challenges\\imagens\\000003.jpg"));
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            
            for(byte[] i : image){
                if(i!=null)
                    outputStream.write(i);
                else break;
            }
          
           this.image = ImageIO.read(new ByteArrayInputStream(outputStream.toByteArray())); 

        } 
        catch (IOException e) 
        { 
          e.printStackTrace();
        } 
      } 

      public void paintComponent(Graphics g) 
      { 
        g.drawImage(image,0, 0,300, 300, null); 
        //repaint(); 
      } 
    }
    
    public class QuestionRunner extends Thread{
        
        byte[] music;
        //boolean answer;
        TimerUpdate timer;
         Player mp3player;
        public QuestionRunner(byte[][] music,TimerUpdate timer) throws IOException{
            
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            for(byte[] m : music){
                if(m!=null)
                    out.write(m);
            }
            
            this.music = out.toByteArray();
            this.timer = timer;
            answer = false;
        }
        
        public void run(){
            
            try {
                ByteArrayInputStream input = new ByteArrayInputStream(music);
                BufferedInputStream in = new BufferedInputStream(input);
                mp3player = new Player(in);
                new MP3Player().start();
               
                while(!answer){
                    int time = (60000 - mp3player.getPosition());
                    if(time<=0)break;
                        timer.timerupdate(time/1000);
                }
                if(answer) dispose();
                mp3player.close();
            } catch (JavaLayerException ex) {
                Logger.getLogger(QuestionGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        public synchronized void closeMp3(){
                this.mp3player.close();
            }

        
        class MP3Player extends Thread{
            public void run(){
                try {
                    mp3player.play();
                } catch (JavaLayerException ex) {
                    Logger.getLogger(QuestionGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    public  class TimerUpdate extends Observable{
        
            public  void timerupdate(int time){        
                this.setChanged();
                this.notifyObservers(time);
            }
        }
    public class AnswerInformer extends Observable{
        public void answer(int question,int opt, int time){
            String s = ""+question+";"+opt+";"+time;
            this.setChanged();
            this.notifyObservers(s);
        }
    }

    public class WindowAdapterImpl extends WindowAdapter {

        public WindowAdapterImpl(AnswerInformer as,JFrame f,QuestionRunner runner) {
            this.ansInfo = as;
             p= runner;
            caller = f;
        }
        AnswerInformer ansInfo;
        JFrame caller;
        QuestionRunner p ;

        @Override
        public void windowClosing(WindowEvent e) {
           
            int confirm = JOptionPane.showOptionDialog(caller, "Quit Challenge?", "Quit Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (confirm==JOptionPane.YES_OPTION) {
                
                
                answer = true;
                this.ansInfo.answer(n_question, -2, time);
                System.out.println("closed Question");
                try{
                    p.closeMp3();
                }catch(NullPointerException ex){
                    System.out.println("-----##----"+ex.getMessage());
                }                
                this.caller.dispose();
            }
        }
    }
}
