/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CLientGUI;

import Client.PDU_Builder;
import Common.PDU;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import javax.swing.JFrame;

/**
 *
 * @author fdr
 */
public class Lobby extends javax.swing.JFrame {

    /**
     * Creates new form Lobby
     */
    
    DatagramSocket socket;
    String user,points;
    Register_Login regsiter_login;
    int label;
    public Lobby() {
        initComponents();
    }

    public Lobby(String nome, String points, DatagramSocket socket, Register_Login rl,int label) throws IOException {
         initComponents();
         this.socket = socket;
         this.user = nome;
         this.points = points;
         this.regsiter_login = rl;
         this.label = label;
         
         PDU request = PDU_Builder.LIST_CHALLENGES(label);
         label++;
         byte[] data = PDU.toBytes(request);
         DatagramPacket packet = new DatagramPacket(data, data.length);
         socket.send(packet);
         
         packet = new DatagramPacket(new byte[1024], 1024);
         socket.receive(packet);
         
         PDU reply = PDU.fromBytes(packet.getData());
         
         if(reply.getData()!=null){
                if(reply.getData()[21]!=null){
                    new ErrorWindow("Erro",new String(reply.getData()[21]),"error", this).wshow();
                }
                else{
                    
                    System.out.println(nome + " " + points );
                    //new Lobby(nome,points,socket,this,label).setVisible(true);
                }
            }
         
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        list_challenges = new javax.swing.JList();
        label_listChallenges = new javax.swing.JLabel();
        button_list_challenges = new javax.swing.JButton();
        panel_user_info = new javax.swing.JPanel();
        ui_nome = new javax.swing.JLabel();
        ui_score = new javax.swing.JLabel();
        label_userInfo_nome = new javax.swing.JLabel();
        label_userInfo_score = new javax.swing.JLabel();
        bt_acceptChallenge = new javax.swing.JButton();
        bt_makeChallenge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(522, 382));

        list_challenges.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Joguinho - 21h:10m:45s do dia 10 de Março de 2015", "Jogatina - 21h:15m:00s do dia 10 de Março de 2015" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_challenges);

        label_listChallenges.setText("Challenges:");

        button_list_challenges.setText("R");

        panel_user_info.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Info:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        ui_nome.setText("Nome:");

        ui_score.setText("Score:");

        javax.swing.GroupLayout panel_user_infoLayout = new javax.swing.GroupLayout(panel_user_info);
        panel_user_info.setLayout(panel_user_infoLayout);
        panel_user_infoLayout.setHorizontalGroup(
            panel_user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_user_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ui_nome)
                    .addComponent(ui_score))
                .addGap(18, 18, 18)
                .addGroup(panel_user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_userInfo_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(label_userInfo_score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_user_infoLayout.setVerticalGroup(
            panel_user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_user_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ui_nome)
                    .addComponent(label_userInfo_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ui_score)
                    .addComponent(label_userInfo_score, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        bt_acceptChallenge.setText("Accept Challenge");

        bt_makeChallenge.setText("Make Challenge");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_listChallenges)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_list_challenges, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 146, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_acceptChallenge, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(bt_makeChallenge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_user_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_makeChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bt_acceptChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel_user_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_list_challenges)
                    .addComponent(label_listChallenges))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_acceptChallenge;
    private javax.swing.JButton bt_makeChallenge;
    private javax.swing.JButton button_list_challenges;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_listChallenges;
    private javax.swing.JLabel label_userInfo_nome;
    private javax.swing.JLabel label_userInfo_score;
    private javax.swing.JList list_challenges;
    private javax.swing.JPanel panel_user_info;
    private javax.swing.JLabel ui_nome;
    private javax.swing.JLabel ui_score;
    // End of variables declaration//GEN-END:variables
}
