/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CLientGUI;

import Client.PDU_Builder;
import Client.User;
import Common.PDU;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author fdr
 */
public class Lobby extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form Lobby
     */
    
    DatagramSocket socket;
    Register_Login regsiter_login;
    int label;
    Map<String,String> activeChallenges;
    User user;
    public Lobby() {
        initComponents();
    }

    public Lobby(String nome, String points, DatagramSocket socket, Register_Login rl,int label,ArrayList<String> strs) throws IOException {
         initComponents();
         this.socket = socket;
         this.user = new User();
         this.user.username = nome;
         this.user.points = Integer.parseInt(points);
         this.regsiter_login = rl;
         this.label = label;   
         this.label_userInfo_nome.setText(this.user.username);
         this.label_userInfo_score.setText(""+this.user.points);
         bt_acceptChallenge.setEnabled(false);
         bt_removeChallenge.setEnabled(false);
         this.activeChallenges = new HashMap<>();
         
         DefaultListModel<String> model = new DefaultListModel<>();
         
         for(String s:strs){
             String parsed = parser(s);
             model.addElement(parsed);
             this.activeChallenges.put(s, parsed);
         }
         
        this.list_challenges.setModel(model);
        this.setLocationRelativeTo(null); 
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        list_challenges = new javax.swing.JList();
        label_listChallenges = new javax.swing.JLabel();
        button_list_challenges = new javax.swing.JButton();
        panel_user_info = new javax.swing.JPanel();
        ui_nome = new javax.swing.JLabel();
        ui_score = new javax.swing.JLabel();
        label_userInfo_nome = new javax.swing.JLabel();
        label_userInfo_score = new javax.swing.JLabel();
        bt_acceptChallenge = new javax.swing.JButton();
        bt_makeChallenge = new javax.swing.JButton();
        bt_removeChallenge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        list_challenges.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Joguinho - 21h:10m:45s do dia 10 de Março de 2015", "Jogatina - 21h:15m:00s do dia 10 de Março de 2015" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        list_challenges.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_challengesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(list_challenges);

        label_listChallenges.setText("Challenges:");

        button_list_challenges.setText("R");
        button_list_challenges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_list_challengesActionPerformed(evt);
            }
        });

        panel_user_info.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Info:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        ui_nome.setText("Nome:");

        ui_score.setText("Score:");

        javax.swing.GroupLayout panel_user_infoLayout = new javax.swing.GroupLayout(panel_user_info);
        panel_user_info.setLayout(panel_user_infoLayout);
        panel_user_infoLayout.setHorizontalGroup(
            panel_user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_user_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ui_nome)
                    .addComponent(ui_score))
                .addGap(18, 18, 18)
                .addGroup(panel_user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_userInfo_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_userInfo_score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_user_infoLayout.setVerticalGroup(
            panel_user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_user_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ui_nome)
                    .addComponent(label_userInfo_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_user_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ui_score)
                    .addComponent(label_userInfo_score, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        bt_acceptChallenge.setText("Accept ");
        bt_acceptChallenge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_acceptChallengeActionPerformed(evt);
            }
        });

        bt_makeChallenge.setText("Make Challenge");
        bt_makeChallenge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_makeChallengeActionPerformed(evt);
            }
        });

        bt_removeChallenge.setText("Remove ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_makeChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_acceptChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_removeChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(panel_user_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_listChallenges)
                        .addGap(360, 360, 360)
                        .addComponent(button_list_challenges, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_makeChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_acceptChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_removeChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panel_user_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(label_listChallenges))
                    .addComponent(button_list_challenges))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_makeChallengeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_makeChallengeActionPerformed
        // TODO add your handling code here:
        buttonBlocktrigger b = new buttonBlocktrigger();
        b.addObserver(this);
        new MakeChallenge(this, true,socket,label,b,this.user).setVisible(true);
    }//GEN-LAST:event_bt_makeChallengeActionPerformed

    private void button_list_challengesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_list_challengesActionPerformed

        try {
            PDU requestPDU = PDU_Builder.LIST_CHALLENGES(label);
            label++;
            byte[] data = PDU.toBytes(requestPDU);
            DatagramPacket packet = new DatagramPacket(data, data.length);
            socket.send(packet);
            packet = new DatagramPacket(new byte[1024], 1024);
            socket.receive(packet);
            PDU reply = PDU.fromBytes(packet.getData());
            byte[][] chs = reply.getData();
            this.activeChallenges = new HashMap<>();
            ArrayList<String> strs = new ArrayList<>();
            if(chs!=null){
                for(byte[] b: chs){
                    String ch = new String(b);
                    strs.add(ch);
                }
            }
            
            //parser
            
            DefaultListModel<String> model = new DefaultListModel<>();
         
            for(String s:strs){
                String parsed = parser(s);
                model.addElement(parsed);
                this.activeChallenges.put(s, parsed); 
            }
         
            this.list_challenges.setModel(model);
        } catch (IOException ex) {
            Logger.getLogger(Lobby.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
    }//GEN-LAST:event_button_list_challengesActionPerformed

    private void list_challengesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_challengesValueChanged
        // TODO add your handling code here:
        bt_acceptChallenge.setEnabled(true);
        bt_removeChallenge.setEnabled(true);
    }//GEN-LAST:event_list_challengesValueChanged

    private void bt_acceptChallengeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_acceptChallengeActionPerformed
        try {
            // TODO add your handling code here:
            int i = this.list_challenges.getSelectedIndex();
            String ch = (String) this.activeChallenges.keySet().toArray()[i];
            String[] parts = ch.split(",");
            PDU pdu = PDU_Builder.ACCEPT_CHALLENGE(label, parts[0]);
            byte[] data = PDU.toBytes(pdu);
            socket.send(new DatagramPacket(data, data.length));
            
            DatagramPacket packet = new DatagramPacket(new byte[1024], 1024);
            socket.receive(packet);
            pdu = PDU.fromBytes(packet.getData());
            
            
            if(pdu.getData()[21]==null){
               buttonBlocktrigger b = new buttonBlocktrigger();
               b.addObserver(this);
               new GameThread(socket, parts[0],parts[1], parts[2], Integer.parseInt(parts[3]), label,b,this.user).start();
            }
            else{
                
            }
            
            this.bt_makeChallenge.setEnabled(false);
            this.bt_acceptChallenge.setEnabled(false);
            this.bt_removeChallenge.setEnabled(false);
            
        } catch (IOException ex) {
            Logger.getLogger(Lobby.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_acceptChallengeActionPerformed

        private String parser(String date){
            
            String[] tokens = date.split(",");
            String nome = tokens[0]+ " - ";
            String hora = tokens[2].substring(0,2)+":h"+tokens[2].substring(2,4)+":m"+tokens[2].substring(4)+":s";
            String ano = "20"+tokens[1].substring(0,2);
            String dia = tokens[1].substring(4);
            String mes = tokens[1].substring(2,4);
            
            switch (mes) {
                case "01":  mes = "January";
                            break;
                case "02":  mes = "February";
                            break;
                case "03":  mes = "March";
                            break;
                case "04":  mes = "April";
                            break;
                case "05":  mes = "May";
                            break;
                case "06":  mes = "June";
                            break;
                case "07":  mes = "July";
                            break;
                case "08":  mes = "August";
                            break;
                case "09":  mes = "September";
                            break;
                case "10":  mes = "October";
                            break;
                case "11":  mes = "November";
                            break;
                case "12":  mes = "December";
                            break;
            }
            String data = dia + " de " + mes + " de " +ano;
            
            return nome+hora+" do"+" dia "+data;
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_acceptChallenge;
    private javax.swing.JButton bt_makeChallenge;
    private javax.swing.JButton bt_removeChallenge;
    private javax.swing.JButton button_list_challenges;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_listChallenges;
    private javax.swing.JLabel label_userInfo_nome;
    private javax.swing.JLabel label_userInfo_score;
    private javax.swing.JList list_challenges;
    private javax.swing.JPanel panel_user_info;
    private javax.swing.JLabel ui_nome;
    private javax.swing.JLabel ui_score;
    // End of variables declaration//GEN-END:variables

    
    public class buttonBlocktrigger extends Observable{
        
        public void blockButtons(){
            this.setChanged();
            this.notifyObservers(false);
        }
        
        public void enableButtons(){
            this.setChanged();
            this.notifyObservers(true);
        }
    }
    
    @Override
    public void update(Observable o, Object arg) {
        boolean b = (boolean)arg;
        this.bt_acceptChallenge.setEnabled(b);
        this.bt_makeChallenge.setEnabled(b);
        this.bt_removeChallenge.setEnabled(b);
        this.button_list_challenges.setEnabled(b);
        //aparece timer para as perguntas!!!!
        //era nice
            //faz update dos pontos
            this.label_userInfo_nome.setText(this.user.username);
            this.label_userInfo_score.setText(""+this.user.points);
        
    }
}
